base_output_dir: '/data/sguo/Processed/2018_11_01_kidney_slice/SMS_2018_1101_1906_1_BG_2018_1101_1906_1/test_2D'
focal_plane_idx: [0, 1]
pos_idx: [3, 4]
verbose: 10
split_volumes: False
splitter_class: LifStackSplitter2D
input_fname: '/home/krishnan/mntDir/DeviceData/CZLASX-01/Data/2017/VirtualStaining/20171121_ManuShalin/ZStack1_BF_Clath_Mito_Nuclei.lif'
correct_flat_field: False
flat_field_class: FlatFieldEstimator2D
use_masks: False
masks:
    mask_channels: [4,5]
    str_elem_radius: 3
tile_stack: True
tile:
    channels: [0, 1]
    tile_size: [256, 256]
    step_size: [128, 128]
    save_cropped_masks: True    
